openapi: 3.0.0
info:
  title: API ArgentBank
  description: Documentation de l'API d'ArgentBank pour la gestion des utilisateurs et transactions.
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
    description: Serveur de développement local

paths:
  /user/login:
    post:
      summary: Authentification utilisateur
      description: Permet aux utilisateurs de se connecter et d'obtenir un token d'authentification.
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/User"
            examples:  # 🛠️ Correction de l'indentation ici
              TonyStark:
                value:
                  email: "tony@stark.com"
                  password: "password123"
              SteveRogers:
                value:
                  email: "steve@rogers.com"
                  password: "password456"
      responses:
        "200":
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "eyJhbGciOiJIUzI1..."
        "401":
          description: Identifiants invalides

  /user/profile:
    get:
      summary: Récupération des informations utilisateur
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
        "401":
          description: Non autorisé
    put:
      summary: Mise à jour du profil utilisateur
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                  example: "newUsername"
      responses:
        "200":
          description: Mise à jour réussie
        "400":
          description: Requête invalide

components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: email
          example: "tony@stark.com"
        password:
          type: string
          format: password
          example: "password123"
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          example: 1
        firstName:
          type: string
          example: "Tony"
        lastName:
          type: string
          example: "Stark"
        userName:
          type: string
          example: "Tonton"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
